var cookList = {
    // Cooking Boxes
    "Guru's Cooking Box - Balenos Meal": {},
    "Guru's Cooking Box - Calpheon Meal": {},
    "Guru's Cooking Box - Kamasylvia Meal": {},
    "Guru's Cooking Box - Margoria Seafood Meal": {},
    "Guru's Cooking Box - Mediah Meal": {},
    "Guru's Cooking Box - O'dyllita Meal": {},
    "Guru's Cooking Box - Serendia Meal": {},
    "Guru's Cooking Box - Special Arehaza Meal": {},
    "Guru's Cooking Box - Special Drieghan Meal": {},
    "Guru's Cooking Box - Valencia Meal": {},
    // Meal List
    'Balenos Meal': {},
    'Calpheon Meal': {},
    'Kamasylvia Meal': {},
    'Margoria Seafood Meal': {},
    'Mediah Meal': {},
    "O'dyllita Meal": {},
    'Serendia Meal': {},
    'Special Arehaza Meal': {},
    'Special Drieghanese Meal': {},
    'Valencia Meal': {},
    // Item List
    'Beer': {},
    'Boiled Bird Eggs': {},
    'Butter-Roasted Lobster': {},
    'Cheese Gratin': {},
    'Cheese Pie': {},
    'Chicken Breast Salad': {},
    'Coconut Cocktail': {},
    'Coconut Fried Fish': {},
    'Coconut Pasta': {},
    'Couscous': {},
    'Dark Pudding': {},
    'Date Palm Wine': {},
    'Delotia Juice': {},
    'Delotia Pudding': {},
    'Exotic Herbal Wine': {},
    'Fig Pie': {},
    'Fish Fillet Salad': {},
    'Freekeh Snake Stew': {},
    'Fruit And Vegetable Salad': {},
    'Fruit Wine': {},
    'Ghormeh Sabzi': {},
    'Grilled Bird Meat': {},
    'Grilled Sausage': {},
    'Grilled Scorpion': {},
    'Ham Sandwich': {},
    'Honeycomb Cookie': {},
    'Honey Wine': {},
    'King of Jungle Hamburg': {},
    'Pan-Fried Oyster': {},
    'Prawn Salad': {},
    'Lean Meat Salad': {},
    'Meat Croquette': {},
    'Meat Pasta': {},
    'Meat Pie': {},
    'Meat Stew': {},
    'Milk Tea': {},
    'Oatmeal': {},
    'Pickled Vegetables': {},
    'Rainbow Button Mushroom Cheese Melt': {},
    'Rainbow Button Mushroom Sandwich': {},
    'Roast Marmot': {},
    'Skewered Llama Cheese Melt': {},
    'Smoked Fish Steak': {},
    'Soft Bread': {},
    'Steak': {},
    'Steamed Prawn': {},
    'Stir-Fried Bird': {},
    'Stir-Fried Bracken and Meat': {},
    'Tea With Fine Scent': {},
    'Teff Bread': {},
    'Teff Sandwich': {},
    'Stir-Fried Vegetables': {},
    'Sute Tea': {},
    // Misc Basic Items
    'Dressing': {},
    'Essence of Liquor': {},
    'Red Sauce': {},
    'Vinegar': {},
    'White Sauce': {},
};

module.exports = cookList;