var cookList = {
    // Meal List
    'Balenos Meal': {},
    'Calpheon Meal': {},
    'Kamasylvia Meal': {},
    "O'dyllita Meal": {},
    'Serendia Meal': {},
    'Valencia Meal': {},
    // Item List
    'Beer': {},
    'Boiled Bird Eggs': {},
    'Cheese Gratin': {},
    'Cheese Pie': {},
    'Chicken Breast Salad': {},
    'Coconut Pasta': {},
    'Couscous': {},
    'Date Palm Wine': {},
    'Delotia Juice': {},
    'Delotia Pudding': {},
    'Exotic Herbal Wine': {},
    'Fig Pie': {},
    'Fish Fillet Salad': {},
    'Freekeh Snake Stew': {},
    'Fruit Wine': {},
    'Grilled Bird Meat': {},
    'Grilled Sausage': {},
    'Grilled Scorpion': {},
    'Ham Sandwich': {},
    'Honeycomb Cookie': {},
    'Honey Wine': {},
    'King of Jungle Hamburg': {},
    'Meat Croquette': {},
    'Meat Pasta': {},
    'Meat Pie': {},
    'Milk Tea': {},
    'Oatmeal': {},
    'Pickled Vegetables': {},
    'Rainbow Button Mushroom Cheese Melt': {},
    'Rainbow Button Mushroom Sandwich': {},
    'Smoked Fish Steak': {},
    'Soft Bread': {},
    'Stir-Fried Bird': {},
    'Stir-Fried Bracken and Meat': {},
    'Tea With Fine Scent': {},
    'Teff Sandwich': {},
    'Stir-Fried Vegetables': {},
    // Misc Basic Items
    'Dressing': {},
    'Essence of Liquor': {},
    'Vinegar': {},
    'White Sauce': {},
    'Red Sauce': {},
}

module.exports = cookList;